server:
  port: 8082
  servlet:
    context-path: /
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
    mode: LEGACYHTML5
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 245MB
file:
  upload-dir: E:\data\server\client\data\
  split-file: E:\data\server\server\split\
